Products
Tanay-J/e-commerce pull request #2
Opened 2022-02-16 18:38 UTC by Tanay-J

A page from Turning Pages ecom store to display all the available books
- Main navigation bar with logo
- Secondary navigation bar
- Section with Filters (Category, Price, Ratings, Language, Format)
- Main section with product cards 
- Footer

Demo:

https://user-images.githubusercontent.com/33786522/154333125-feca4022-1690-4295-9c4f-f6d5cef70694.mp4

2022-02-16 19:18 UTC, adith-a-danthi requested changes
Clean code. Looks good. Image tags are missing `alt` attributes, suggest adding them for accessibility.

2022-02-16 19:18 UTC, adith-a-danthi commented on pages/products.html
> +        <img class="brand-logo" src="/assets/Turning Pages-1.png">
Missing `alt` attribute.

2022-02-16 19:30 UTC, sharathnair9999 approved these changes

2022-02-17 07:25 UTC, adith-a-danthi approved these changes

2022-02-17 07:56 UTC, Tanay-J commented
Incorporated the suggested changes. Mergin to dev.

2022-02-17 07:56 UTC, merged